### PR TITLE
Add config.yml file checker

### LINKED ISSUE #149: Add configuration validation option
To enable better automation & confidence in configuration changes prior to reloading the tool, implement a configuration validation option similar to many other software.

The use case is to support a workflow:
1. Make changes to the program configuration.
2. Run configuration validation, ensuring that the configuration can be loaded correctly.
3. Reload or restart running service.

This workflow can also support automation for configuration management, e.g. using Ansible to deploy and validate an updated configuration before restarting the service.

Scope of validation:
- YAML config is valid/no syntax issues
- Basic ThreatIngestor config is viable, no missing required options or conflicting parameters, etc.

### PR DESCRIPTION
**Pull request by ghost**
Prerequisites:
- Must have `yamllint` installed (https://pypi.org/project/yamllint/)

How to test:
- Run the `validate.py` script against the `config.yml` file (`python3 scripts/validate.py config.yml`)
- A verbose flag is also available for more output (`python3 scripts/validate.py config.yml v`)

### CODE REVIEW

**Comment by dspruell-i01** [comment]
@azazelm3dj3d How would you feel about implementing the verbose flag as a standard getopt style `-v`?

**Comment by azazelm3dj3d** [comment]
I plan to add argparse once I've thoroughly tested everything, so that'll be the default way to access arguments other than the file name

**Comment by dspruell-i01** [comment]
> I plan to add argparse once I've thoroughly tested everything, so that'll be the default way to access arguments other than the file name

@azazelm3dj3d Makes sense! I'd like to consider folding this in as supported functionality in the main ThreatIngestor command line tool (and yamllint into the list of installed dependencies).

Do you have output or screenshot of running the validator against a config file and showing success and/or failure? Review looks good to me, I think that type of output would be good to include for reviews going forward.

**Review by dspruell-i01 — APPROVED** [review]
Looks good to me, I'd recommend including a screenshot or textual output showing a run of the validator for review.

**Comment by azazelm3dj3d** [comment]
> @azazelm3dj3d Makes sense! I'd like to consider folding this in as supported functionality in the main ThreatIngestor command line tool (and yamllint into the list of installed dependencies).

The main ThreatIngestor codebase already checks for errors in the configuration during execution, it's just not as elegant as this script. As for [yamllint](https://yamllint.readthedocs.io/en/stable/index.html), we can add it as a dependency, but as far as I know, it can't be used as a library, so it would just clutter up the core dependencies. If anything, it should be installed on an as-use basis since it's an independent script.

@dspruell-i01 Added more checks and improved output. No longer uses the `-v` flag since the whole point is to notify the user based on the validation response.

**Pull request merged**
